[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "launchpy"
authors = [
    {name = "Julien Piccini", email = "piccini.julien@gmail.com"},
]
description = "Adobe Launch API wrapper"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.10"
keywords = ["adobe", "analytics", "API", "python"]
license = {text = "Apache License 2.0"}
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Development Status :: 4 - Beta"
]
dependencies = ['pandas', 
                "requests",
                 "pathlib2", 
                 "pathlib",
                 "aepp",
                 "rich",
                 "deprecated"]

[project.urls]
homepage = "https://github.com/pitchmuc/launchpy"
changelog = "https://github.com/pitchmuc/launchpy/blob/master/docs/releases.md"

[tool.setuptools.dynamic]
version = {attr = "launchpy.__version__.__version__"}

[project.scripts]
launchpy = "launchpy.cli.__main__:main"

[tool.setuptools]
packages = ["launchpy", "launchpy.cli"]
include-package-data = true